### ISSUE TITLE
Migranti residenti: il 7% della popolazione leccese, più le donne, aumentano i minori

### ISSUE THREAD

**Issue by trimanu** [ondata/migranti-lecce#4]
Autori: Andrea Aufieri - Manuela Tritto
Testo - Nel 2016, la presenza di persone immigrate residenti a Lecce, al netto dei presenti temporaneamente o in attesa della carta d’identità, è stata di 6.689 unità, il 7% della popolazione locale. Di 2,4 punti percentuali in meno rispetto alla media nazionale, che è del 9,4%. Tra i residenti stranieri c’è una lieve prevalenza delle donne: sono 3.371, mentre  gli uomini sono 3.318. Su scala provinciale la differenza è più accentuata: 12.160 le donne, 10.379  gli uomini. La prevalenza della componente femminile aumenta man mano che il dato diventa regionale (64.554 donne rispetto a 58.168 uomini) e nazionale (2.644.666 rispetto a 2.381.487). Un approfondimento sulla presenza dei minori. Nel 2016, i minori stranieri presenti in Italia sono 70.053; in Puglia 1.542; in provincia di Lecce 232, 78 solo nel comune di Lecce. Una situazione particolare è quelle dei minori stranieri non accompagnati, cioè minori che arrivano in Italia senza alcun adulto di riferimento. Il fenomeno comincia a delinearsi negli anni ‘90 e risulta in costante aumento. I dati del Ministero delle Politiche sociali ci dicono che al 31 dicembre 2015 i m.s.n.a in Puglia sono 1.102 e rappresentano il 9,2% del totale delle presenze in Italia.
In Puglia, le strutture di accoglienza in cui sono presenti m. s.n. a.sono 102. La Puglia rientra tra le prime 5 regioni per maggior numero di strutture presenti. I comuni pugliesi che aderiscono alla rete dei comuni del Programma Nazionale sono Bari, Brindisi e Lecce.

**Comment by nelsonmau** [comment]
grazie @trimanu! ho aggiornato il testo e lo vedi online qui 
https://ondata.github.io/migranti-lecce/

se tutto ok, rispondimi qui e clicca qui in in basso per chiudere la issue

grazie!

**Comment by trimanu** [comment]
tutto ok.
